//
//  FeaturedTableViewController.swift
//  WordPressApp
//
//  Created by Steven Taglohner on 07/02/2018.
//  Copyright © 2018 Steven Taglohner. All rights reserved.
//

import UIKit

class FeaturedTableViewController: UITableViewController {
    
    var postArray = [
        
        PostObject(title: "Office for Mac buying guide 2018", excerpt: "Everything you need to know about Office for Mac & which version you should buy", postPicture: #imageLiteral(resourceName: "Post1"), authorName: "Steven Taglöhner", authorPicture: #imageLiteral(resourceName: "Steven"), postDate: "Today", isFeatured: false),
        PostObject(title: "MarioKart Tour for iOS release date, platforms and gameplay rumours", excerpt: "Here’s everything we know so far about MarioKart Tour, from the latest release date rumours to what we’d like to see from gameplay", postPicture: #imageLiteral(resourceName: "Post2"), authorName: "Konrad Taglöhner", authorPicture: #imageLiteral(resourceName: "Konrad"), postDate: "Yesterday", isFeatured: false),
        PostObject(title: "Best Mac email clients of 2018", excerpt: "Apple's Mail app is great, but sometimes we need something a little more... Feature rich. Here are some of the best alternatives", postPicture: #imageLiteral(resourceName: "Post3"), authorName: "Susan S Kim", authorPicture: #imageLiteral(resourceName: "Susan"), postDate: "03/02/2018", isFeatured: false),
        PostObject(title: "How to use iOS 11 Settings on iPhone & iPad", excerpt: "Our comprehensive guide to the settings you need to know in iOS 11: personalise your iPhone or iPad to work the way you want it to", postPicture: #imageLiteral(resourceName: "Post4"), authorName: "Steven Taglöhner", authorPicture: #imageLiteral(resourceName: "Steven"), postDate: "28/01/2018", isFeatured: false),
        PostObject(title: "Apple Q1 2018 financial results: Highest ever quarterly revenue", excerpt: "Apple has announced financial results for Q1 2018, its best ever quarter. Find out how many iPhones, iPads & Macs Apple sold", postPicture: #imageLiteral(resourceName: "Post5"), authorName: "Milena Bonfim", authorPicture: #imageLiteral(resourceName: "avatar"), postDate: "14/01/2018", isFeatured: false),
        PostObject(title: "iOS 11 update: latest version, problems, fixes & features", excerpt: "Everything you need to know about the new iOS 11, including the latest version, any issues, new features and compatible devices", postPicture: #imageLiteral(resourceName: "Post6"), authorName: "Brenda Cariz", authorPicture: #imageLiteral(resourceName: "Elvis"), postDate: "29/12/2017", isFeatured: false),
        PostObject(title: "Office for Mac buying guide 2018", excerpt: "Everything you need to know about Office for Mac & which version you should buy", postPicture: #imageLiteral(resourceName: "Post1"), authorName: "Steven Taglöhner", authorPicture: #imageLiteral(resourceName: "Steven"), postDate: "Today", isFeatured: false),
        PostObject(title: "MarioKart Tour for iOS release date, platforms and gameplay rumours", excerpt: "Here’s everything we know so far about MarioKart Tour, from the latest release date rumours to what we’d like to see from gameplay", postPicture: #imageLiteral(resourceName: "Post2"), authorName: "Konrad Taglöhner", authorPicture: #imageLiteral(resourceName: "Konrad"), postDate: "Yesterday", isFeatured: false),
        PostObject(title: "Best Mac email clients of 2018", excerpt: "Apple's Mail app is great, but sometimes we need something a little more... Feature rich. Here are some of the best alternatives", postPicture: #imageLiteral(resourceName: "Post3"), authorName: "Susan S Kim", authorPicture: #imageLiteral(resourceName: "Susan"), postDate: "03/02/2018", isFeatured: false),
        PostObject(title: "How to use iOS 11 Settings on iPhone & iPad", excerpt: "Our comprehensive guide to the settings you need to know in iOS 11: personalise your iPhone or iPad to work the way you want it to", postPicture: #imageLiteral(resourceName: "Post4"), authorName: "Steven Taglöhner", authorPicture: #imageLiteral(resourceName: "Steven"), postDate: "28/01/2018", isFeatured: false),
        PostObject(title: "Apple Q1 2018 financial results: Highest ever quarterly revenue", excerpt: "Apple has announced financial results for Q1 2018, its best ever quarter. Find out how many iPhones, iPads & Macs Apple sold", postPicture: #imageLiteral(resourceName: "Post5"), authorName: "Milena Bonfim", authorPicture: #imageLiteral(resourceName: "avatar"), postDate: "14/01/2018", isFeatured: false),
        PostObject(title: "iOS 11 update: latest version, problems, fixes & features", excerpt: "Everything you need to know about the new iOS 11, including the latest version, any issues, new features and compatible devices", postPicture: #imageLiteral(resourceName: "Post6"), authorName: "Brenda Cariz", authorPicture: #imageLiteral(resourceName: "Elvis"), postDate: "29/12/2017", isFeatured: false),
        PostObject(title: "Office for Mac buying guide 2018", excerpt: "Everything you need to know about Office for Mac & which version you should buy", postPicture: #imageLiteral(resourceName: "Post1"), authorName: "Steven Taglöhner", authorPicture: #imageLiteral(resourceName: "Steven"), postDate: "Today", isFeatured: false),
        PostObject(title: "MarioKart Tour for iOS release date, platforms and gameplay rumours", excerpt: "Here’s everything we know so far about MarioKart Tour, from the latest release date rumours to what we’d like to see from gameplay", postPicture: #imageLiteral(resourceName: "Post2"), authorName: "Konrad Taglöhner", authorPicture: #imageLiteral(resourceName: "Konrad"), postDate: "Yesterday", isFeatured: false),
        PostObject(title: "Best Mac email clients of 2018", excerpt: "Apple's Mail app is great, but sometimes we need something a little more... Feature rich. Here are some of the best alternatives", postPicture: #imageLiteral(resourceName: "Post3"), authorName: "Susan S Kim", authorPicture: #imageLiteral(resourceName: "Susan"), postDate: "03/02/2018", isFeatured: false),
        PostObject(title: "How to use iOS 11 Settings on iPhone & iPad", excerpt: "Our comprehensive guide to the settings you need to know in iOS 11: personalise your iPhone or iPad to work the way you want it to", postPicture: #imageLiteral(resourceName: "Post4"), authorName: "Steven Taglöhner", authorPicture: #imageLiteral(resourceName: "Steven"), postDate: "28/01/2018", isFeatured: false),
        PostObject(title: "Apple Q1 2018 financial results: Highest ever quarterly revenue", excerpt: "Apple has announced financial results for Q1 2018, its best ever quarter. Find out how many iPhones, iPads & Macs Apple sold", postPicture: #imageLiteral(resourceName: "Post5"), authorName: "Milena Bonfim", authorPicture: #imageLiteral(resourceName: "avatar"), postDate: "14/01/2018", isFeatured: false),
        PostObject(title: "iOS 11 update: latest version, problems, fixes & features", excerpt: "Everything you need to know about the new iOS 11, including the latest version, any issues, new features and compatible devices", postPicture: #imageLiteral(resourceName: "Post6"), authorName: "Brenda Cariz", authorPicture: #imageLiteral(resourceName: "Elvis"), postDate: "29/12/2017", isFeatured: false),
        PostObject(title: "Office for Mac buying guide 2018", excerpt: "Everything you need to know about Office for Mac & which version you should buy", postPicture: #imageLiteral(resourceName: "Post1"), authorName: "Steven Taglöhner", authorPicture: #imageLiteral(resourceName: "Steven"), postDate: "Today", isFeatured: true),
        PostObject(title: "MarioKart Tour for iOS release date, platforms and gameplay rumours", excerpt: "Here’s everything we know so far about MarioKart Tour, from the latest release date rumours to what we’d like to see from gameplay", postPicture: #imageLiteral(resourceName: "Post2"), authorName: "Konrad Taglöhner", authorPicture: #imageLiteral(resourceName: "Konrad"), postDate: "Yesterday", isFeatured: true),
        PostObject(title: "Best Mac email clients of 2018", excerpt: "Apple's Mail app is great, but sometimes we need something a little more... Feature rich. Here are some of the best alternatives", postPicture: #imageLiteral(resourceName: "Post3"), authorName: "Susan S Kim", authorPicture: #imageLiteral(resourceName: "Susan"), postDate: "03/02/2018", isFeatured: true),
        PostObject(title: "How to use iOS 11 Settings on iPhone & iPad", excerpt: "Our comprehensive guide to the settings you need to know in iOS 11: personalise your iPhone or iPad to work the way you want it to", postPicture: #imageLiteral(resourceName: "Post4"), authorName: "Steven Taglöhner", authorPicture: #imageLiteral(resourceName: "Steven"), postDate: "28/01/2018", isFeatured: true),
        PostObject(title: "Apple Q1 2018 financial results: Highest ever quarterly revenue", excerpt: "Apple has announced financial results for Q1 2018, its best ever quarter. Find out how many iPhones, iPads & Macs Apple sold", postPicture: #imageLiteral(resourceName: "Post5"), authorName: "Milena Bonfim", authorPicture: #imageLiteral(resourceName: "avatar"), postDate: "14/01/2018", isFeatured: true),
        PostObject(title: "iOS 11 update: latest version, problems, fixes & features", excerpt: "Everything you need to know about the new iOS 11, including the latest version, any issues, new features and compatible devices", postPicture: #imageLiteral(resourceName: "Post6"), authorName: "Brenda Cariz", authorPicture: #imageLiteral(resourceName: "Elvis"), postDate: "29/12/2017", isFeatured: true),
        PostObject(title: "Office for Mac buying guide 2018", excerpt: "Everything you need to know about Office for Mac & which version you should buy", postPicture: #imageLiteral(resourceName: "Post1"), authorName: "Steven Taglöhner", authorPicture: #imageLiteral(resourceName: "Steven"), postDate: "Today", isFeatured: true),
        PostObject(title: "MarioKart Tour for iOS release date, platforms and gameplay rumours", excerpt: "Here’s everything we know so far about MarioKart Tour, from the latest release date rumours to what we’d like to see from gameplay", postPicture: #imageLiteral(resourceName: "Post2"), authorName: "Konrad Taglöhner", authorPicture: #imageLiteral(resourceName: "Konrad"), postDate: "Yesterday", isFeatured: true),
        PostObject(title: "Best Mac email clients of 2018", excerpt: "Apple's Mail app is great, but sometimes we need something a little more... Feature rich. Here are some of the best alternatives", postPicture: #imageLiteral(resourceName: "Post3"), authorName: "Susan S Kim", authorPicture: #imageLiteral(resourceName: "Susan"), postDate: "03/02/2018", isFeatured: true),
        PostObject(title: "How to use iOS 11 Settings on iPhone & iPad", excerpt: "Our comprehensive guide to the settings you need to know in iOS 11: personalise your iPhone or iPad to work the way you want it to", postPicture: #imageLiteral(resourceName: "Post4"), authorName: "Steven Taglöhner", authorPicture: #imageLiteral(resourceName: "Steven"), postDate: "28/01/2018", isFeatured: true),
        PostObject(title: "Apple Q1 2018 financial results: Highest ever quarterly revenue", excerpt: "Apple has announced financial results for Q1 2018, its best ever quarter. Find out how many iPhones, iPads & Macs Apple sold", postPicture: #imageLiteral(resourceName: "Post5"), authorName: "Milena Bonfim", authorPicture: #imageLiteral(resourceName: "avatar"), postDate: "14/01/2018", isFeatured: true),
        PostObject(title: "iOS 11 update: latest version, problems, fixes & features", excerpt: "Everything you need to know about the new iOS 11, including the latest version, any issues, new features and compatible devices", postPicture: #imageLiteral(resourceName: "Post6"), authorName: "Brenda Cariz", authorPicture: #imageLiteral(resourceName: "Elvis"), postDate: "29/12/2017", isFeatured: true),
        PostObject(title: "Office for Mac buying guide 2018", excerpt: "Everything you need to know about Office for Mac & which version you should buy", postPicture: #imageLiteral(resourceName: "Post1"), authorName: "Steven Taglöhner", authorPicture: #imageLiteral(resourceName: "Steven"), postDate: "Today", isFeatured: true),
        PostObject(title: "MarioKart Tour for iOS release date, platforms and gameplay rumours", excerpt: "Here’s everything we know so far about MarioKart Tour, from the latest release date rumours to what we’d like to see from gameplay", postPicture: #imageLiteral(resourceName: "Post2"), authorName: "Konrad Taglöhner", authorPicture: #imageLiteral(resourceName: "Konrad"), postDate: "Yesterday", isFeatured: true),
        PostObject(title: "Best Mac email clients of 2018", excerpt: "Apple's Mail app is great, but sometimes we need something a little more... Feature rich. Here are some of the best alternatives", postPicture: #imageLiteral(resourceName: "Post3"), authorName: "Susan S Kim", authorPicture: #imageLiteral(resourceName: "Susan"), postDate: "03/02/2018", isFeatured: true),
        PostObject(title: "How to use iOS 11 Settings on iPhone & iPad", excerpt: "Our comprehensive guide to the settings you need to know in iOS 11: personalise your iPhone or iPad to work the way you want it to", postPicture: #imageLiteral(resourceName: "Post4"), authorName: "Steven Taglöhner", authorPicture: #imageLiteral(resourceName: "Steven"), postDate: "28/01/2018", isFeatured: true),
        PostObject(title: "Apple Q1 2018 financial results: Highest ever quarterly revenue", excerpt: "Apple has announced financial results for Q1 2018, its best ever quarter. Find out how many iPhones, iPads & Macs Apple sold", postPicture: #imageLiteral(resourceName: "Post5"), authorName: "Milena Bonfim", authorPicture: #imageLiteral(resourceName: "avatar"), postDate: "14/01/2018", isFeatured: true),
        PostObject(title: "iOS 11 update: latest version, problems, fixes & features", excerpt: "Everything you need to know about the new iOS 11, including the latest version, any issues, new features and compatible devices", postPicture: #imageLiteral(resourceName: "Post6"), authorName: "Brenda Cariz", authorPicture: #imageLiteral(resourceName: "Elvis"), postDate: "29/12/2017", isFeatured: true)
    ]
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        tableView.register(FeaturedTableCollectionViewCell.self, forCellReuseIdentifier: "FeaturedFirstCell")
        tableView.register(BaseTableViewCell.self, forCellReuseIdentifier: "BaseCell")
    }
    
    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        
        return 120
    }
    
    
}

